Spsh 740
dBildungsplattform/dbildungs-iam-keycloak pull request #73
Opened 2024-10-28 14:49 UTC by kristoff-kiefer

# Description

## Links to Tickets or other PRs

https://ticketsystem.dbildungscloud.de/browse/SPSH-740

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-10-28 16:03 UTC, niklaskoopmann approved these changes

2024-10-30 09:51 UTC, marode-cap requested changes

2024-10-30 09:51 UTC, marode-cap commented on charts/dbildungs-iam-keycloak/dev-realm-spsh.json
> +    "passwordPolicy": "maxAuthAge(0) and passwordHistory(3) and length(8) and digits(1) and upperCase(1) and specialChars(1)",
Should also contain `lowerCase(1)` (Ticket was missing this, confirmed by Christian)

2024-11-20 09:18 UTC, niklaskoopmann approved these changes

2024-11-20 13:42 UTC, YoussefBouch approved these changes

2024-11-21 16:10 UTC, merged